name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8' 
        mysql database: 'walker'
        mysql user: 'walker'
        mysql password: ${{ secrets.MYSQL_PASSWORD }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run : ./gradlew test

